### ISSUE TITLE
Is each dataset trained separately or together?

### ISSUE THREAD

**Issue by zezhishao** [real2fish/CSL#1]
Hi, thanks for your great work. 

I wonder how the unsupervised learning is conducted. Is each dataset trained separately or together?

Sincerely,
Zezhi Shao

**Comment by real2fish** [comment]
Dear Zezhi,

Thanks for your appreciation. 
Each dataset is trained separately.

Best regards,
Zhiyu Liang

**Comment by zezhishao** [comment]
I get it! Thanks for you timely reply!
