### ISSUE TITLE
Error in the code

### ISSUE THREAD

**Issue by miladsoltany** [real2fish/CSL#2]
Hello. Awesome work!

I have an issue with the code. In line 206 of UEA.py, where the value of 'ls' is set:

ls=args.lmd-s,

There is an 's' parameter which has not been specified throughout the code. Could you please give some insight as to what the value for this variable should be?

Thank you.

**Comment by real2fish** [comment]
ls (lmd-s) corresponds to the weight of the loss $\mathcal{L}_S$. The default value is 1.0 as specified in line 45 of UEA.py.
